import React, { useEffect, useState } from 'react';
import { FaFileMedical, FaTrash } from 'react-icons/fa';
import { formatDate } from '../../utils/helper';

export const TestHistory = () => {
  const [reports, setReports] = useState([]);

  useEffect(() => {
    const saved = localStorage.getItem('smart_organ_lab_reports');
    if (saved) {
      setReports(JSON.parse(saved));
    }
  }, []);

  const handleDelete = (repId) => {
    if (window.confirm('Are you sure you want to delete this lab report record?')) {
      const saved = localStorage.getItem('smart_organ_lab_reports') || '[]';
      const parsed = JSON.parse(saved);
      const updated = parsed.filter(r => r.id !== repId);
      localStorage.setItem('smart_organ_lab_reports', JSON.stringify(updated));

      setReports(reports.filter(r => r.id !== repId));
    }
  };

  return (
    <div className="tab-content-panel">
      <div className="panel-header">
        <div>
          <h3>Laboratory Test Logs</h3>
          <p>Historical registry of biochemistry and immunogenetics panels generated by Metro Diagnostics.</p>
        </div>
      </div>

      <div className="table-responsive">
        {reports.length > 0 ? (
          <table className="data-table">
            <thead>
              <tr>
                <th>Log Code</th>
                <th>Patient Name</th>
                <th>Diagnostic Panel</th>
                <th>Uploaded Filename</th>
                <th>Date Logged</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((rep) => (
                <tr key={rep.id}>
                  <td style={{ fontWeight: '700' }}>{rep.id}</td>
                  <td style={{ fontWeight: '600' }}>{rep.patientName}</td>
                  <td style={{ fontWeight: '500' }}>{rep.testName}</td>
                  <td style={{ color: 'var(--primary-color)', fontSize: '0.85rem' }}>{rep.fileName}</td>
                  <td>{formatDate(rep.date)}</td>
                  <td>
                    <span className="badge badge-success">{rep.status}</span>
                  </td>
                  <td>
                    <button 
                      className="btn btn-danger" 
                      style={{ padding: '6px 12px', fontSize: '0.78rem' }}
                      onClick={() => handleDelete(rep.id)}
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <div style={{ padding: '40px', textAlign: 'center', opacity: 0.6 }}>
            <FaFileMedical style={{ fontSize: '3rem', marginBottom: '10px' }} />
            <h4>No uploaded logs on file</h4>
            <p style={{ fontSize: '0.85rem', marginTop: '4px' }}>
              Upload test reports to generate lab ledger entries.
            </p>
          </div>
        )}
      </div>
    </div>
  );
};
export default TestHistory;
